name: build
permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  build:
    runs-on: windows-latest
    env:
      BUILD_TYPE: Release

    steps:
    - name: Checkout Repo
      uses: actions/checkout@main
      with:
        path: llvm-msvc
        submodules: 'recursive'

    - name: Install LLVM-MSVC Toolset
      shell: powershell
      run: |
        $releases = Invoke-RestMethod "https://api.github.com/repos/backengineering/llvm-msvc/releases/latest"
        $installer = $releases.assets | Where-Object { $_.name -like "*installer-PDB*" } | Select-Object -First 1
        Invoke-WebRequest -Uri $installer.browser_download_url -OutFile "llvm-msvc-installer.exe"
        Start-Process -FilePath "llvm-msvc-installer.exe" -ArgumentList "/S" -Wait

    - name: Build llvm-msvc
      shell: powershell
      run: |
        cmake -Bbuild -G "Visual Studio 17 2022" -T "LLVM-MSVC_v143" -A x64 `
          -DCMAKE_CXX_FLAGS="/utf-8" `
          -DCMAKE_C_FLAGS="/utf-8" `
          -DLLVM_ENABLE_RPMALLOC=ON `
          -DLLVM_INCLUDE_TESTS=OFF `
          -DLLVM_INCLUDE_EXAMPLES=OFF `
          -DLLDB_ENABLE_PYTHON=OFF `
          -DLLVM_ENABLE_LIBXML2=OFF `
          -DLLVM_ENABLE_ZLIB=OFF `
          -DLLVM_USE_CRT_RELEASE=MT `
          -DLLVM_OBFUSCATION_LINK_INTO_TOOLS=ON `
          -DCMAKE_INSTALL_PREFIX=install `
          -DLLVM_TARGETS_TO_BUILD="X86" `
          -DLLVM_ENABLE_PROJECTS="clang;lld;lldb;compiler-rt" `
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} `
          llvm-msvc\\llvm
        cmake --build build --config ${{ env.BUILD_TYPE }} --target install --parallel 4 -- /p:CL_MPcount=4

    - name: Package
      run: 7z a -t7z -mmt -mf -mhc -mhcf -m0=LZMA2 -mx=9 windows-llvm-msvc.7z install

    - name: Upload Artifact
      uses: actions/upload-artifact@main
      with:
        name: windows-llvm-msvc
        path: windows-llvm-msvc.7z

    - name: Release
      uses: softprops/action-gh-release@master
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        prerelease: ${{ !startsWith(github.ref, 'refs/tags/v') || contains(github.ref, '-pre') }}
        files: windows-llvm-msvc.7z
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
